[database]
host = "localhost"
port = "5432"
name = "ihor"
user = "ihor"
password = ""

[schemas]
#pattern = "api%"
#procPattern = "%----%"

[schemas.dict]
#pattern = "get_user_zahid_list"
proc = ["get_user_zahid_list"]

#[schemas.doc]
#[schemas.perm]
#pattern = "common%"

