[database]
host = "localhost"
port = "5432"
name = "ihor"
user = "ihor"
password = ""

[schemas]
#pattern = "api%"
#procPattern = "%----%"

[schemas.report]
#pattern = "common%"
#proc = ["one", "common_user_insert"]

#[schemas.doc]
#[schemas.perm]
#pattern = "common%"

