[database]
host = "localhost"
port = "5432"
name = "ihor"
user = "ihor"
password = ""

[schemas]
#pattern = "api%"
#procPattern = "%----%"

#[schemas.api]
#pattern = "common%"
#proc = ["one", "common_user_insert"]

#[schemas.dict]
#pattern = "%%"
#tables = ["one", "two"]

